x-common-general: &common-general
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 512M

services:
  pixl:
    <<: *common-general
    image: ghcr.io/pixlgalaxy/pixl
    container_name: pixl
    env_file: .env
    networks:
      - net
    volumes:
      - pixl:/app/scripts

networks:
  net:

volumes:
  pixl:
